### ISSUE TITLE
Create a function add that takes a String and returns a String:

### ISSUE THREAD

**Issue by Mohamed-Waiel-Shikfa** [Mohamed-Waiel-Shikfa/TDD---Ironically-we-don-t-have-a-team-name.#1]
First step
Create a function add that takes a String and returns a String:

String add(String number)
The method can take 0, 1 or 2 numbers separated by comma, and returns their sum.
An empty string will return “0”.
Example of inputs: "", "1", "1.1,2.2".

**Comment by RobbyTato** [comment]
Implemented
